version: "3.9"

########################################################################
########################### SERVICES ###################################
########################################################################
services:
  yocto-local:
    container_name: yocto-local
    image: gitea.estalor.com/tom/yocto-builder:latest
    tty: true
    ports:
      - "$YOCTO_TOASTER_PORT:8000"
    security_opt:
      - no-new-privileges=true
    restart: always
    volumes:
      - /cache:/cache
      - $YOCTO_PROJECT_PATH:$YOCTO_PROJECT_PATH
    environment:
      - TEMPLATECONF=$YOCTO_PROJECT_PATH/layers/meta-estalor/conf/templates/estalor