version: "3.9"

########################################################################
########################### Secrets ####################################
########################################################################
secrets:
  mysql_root_password:
    file: $DOCKERDIR/secrets/mysql_root_password

########################################################################
########################### SERVICES ###################################
########################################################################
services:
  ########################################################################
  # MariaDB - MySQL Database for Gitea
  ########################################################################
  mariadb-gitea:
    container_name: mariadb-gitea
    image: lscr.io/linuxserver/mariadb:latest
    volumes:
      - $DOCKERDIR/appdata/mariadb-gitea/data:/config
    networks:
      home_internal:
    security_opt:
      - no-new-privileges:true
    restart: always
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      MYSQL_ROOT_PASSWORD: $GITEA_ROOT_PASSWORD
      MYSQL_DATABASE: gitea
      MYSQL_USER: $GITEA_MYSQL_USER
      MYSQL_PASSWORD: $GITEA_PASSWORD

  ########################################################################
  # MariaDB - MySQL Database for Guacamole
  ########################################################################
  mariadb-guacemole:
    container_name: mariadb-guacemole
    image: lscr.io/linuxserver/mariadb:latest
    volumes:
      - $DOCKERDIR/appdata/mariadb-guacemole/data:/config
    networks:
      home_internal:
    security_opt:
      - no-new-privileges:true
    restart: always
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      MYSQL_ROOT_PASSWORD: $GUACEMOLE_PASSWORD

  ########################################################################
  # MariaDB - MyQSL Database for Crowdsec
  ########################################################################
  mariadb-crowdsec:
    container_name: mariadb-crowdsec
    image: lscr.io/linuxserver/mariadb:latest
    volumes:
      - $DOCKERDIR/appdata/mariadb-crowdsec/data:/config
      # - $DOCKERDIR/shared/init:/docker-entrypoint-initdb.d
      - $DOCKERDIR/shared/init/init.sql:/data/application/init.sql
    networks:
      home_internal:
    security_opt:
      - no-new-privileges:true
    restart: always
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      FILE__MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password # Note FILE__ (double underscore) - Issue #127
      MYSQL_DATABASE: crowdsec
      MYSQL_USER: crowdsec
      MYSQL_PASSWORD: crowdsec
    secrets:
      - mysql_root_password