version: "3.9"

########################################################################
########################### SERVICES ###################################
########################################################################
services:
  ########################################################################
  # DockerGC - Automatic cleanup of images and containers
  ########################################################################
  dockergc:
    container_name: dockergc
    image: clockworksoul/docker-gc-cron:latest
    networks:
      home_internal:
      socket_proxy:
    security_opt:
      - no-new-privileges:true
    restart: always
    volumes:
      - $DOCKERDIR/appdata/docker-gc/docker-gc-exclude:/etc/docker-gc-exclude # Create empty file
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375
      CRON: 0 0 0 * * ? # Everyday at midnight. Previously 0 0 * * *
      FORCE_IMAGE_REMOVAL: 1
      FORCE_CONTAINER_REMOVAL: 0
      GRACE_PERIOD_SECONDS: 604800
      DRY_RUN: 0
      CLEAN_UP_VOLUMES: 1
      TZ: $TZ

  ########################################################################
  # Watchtower - Automatic container updater
  ########################################################################
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    networks:
      socket_proxy:
    security_opt:
      - no-new-privileges:true
    restart: always
    environment:
      TZ: $TZ
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_REMOVE_VOLUMES: "true"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_NO_STARTUP_MESSAGE: "false"
      WATCHTOWER_SCHEDULE: "0 30 12 * * *" # Everyday at 12:30
      DOCKER_HOST: tcp://socket-proxy:2375
      DOCKER_API_VERSION: "1.40"

  ########################################################################
  # Socket-proxy - Security Enchanced Proxy for Docker Socket
  ########################################################################
  socket-proxy:
    container_name: socket-proxy
    image: tecnativa/docker-socket-proxy:latest
    networks:
      home_internal:
      socket_proxy:
        ipv4_address: 192.168.91.254 # You can specify a static IP
    security_opt:
      - no-new-privileges:true
    restart: always
    ports:
      - "127.0.0.1:2375:2375" # Port 2375 should only ever get exposed to the internal network
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - LOG_LEVEL=info # debug,info,notice,warning,err,crit,alert,emerg
      ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      # 0 to revoke access.
      # 1 to grant access.
      ## Granted by Default
      - EVENTS=1
      - PING=1
      - VERSION=1
      ## Revoked by Default
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=1 # Watchtower
      # Not always needed
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1 # Traefik, portainer, etc.
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1 # Portainer
      - INFO=1 # Portainer
      - NETWORKS=1 # Portainer
      - NODES=0
      - PLUGINS=0
      - SERVICES=1 # Portainer
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1 # Portainer
      - VOLUMES=1 # Portainer