version: "3.9"

########################################################################
########################### SERVICES ###################################
########################################################################
services:
  ########################################################################
  # NodeRed
  ########################################################################
  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    networks:
      home_internal:
    security_opt:
      - no-new-privileges:true
    restart: always
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    volumes:
      - $DOCKERDIR/appdata/nodered/data:/data
    ports:
      - "1880:1880"
    depends_on:
      - home-assistant
      - mosquitto-mqtt
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.nodered-rtr.entrypoints=https"
      - "traefik.http.routers.nodered-rtr.rule=Host(`nodered.$DOMAINNAME_CLOUD_SERVER`)"
      ## Middlewares
      - "traefik.http.routers.nodered-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.nodered-rtr.service=nodered-svc"
      - "traefik.http.services.nodered-svc.loadbalancer.server.port=1880"
      ## Watchtower manual update
      - "com.centurylinklabs.watchtower.enable=false"

  ########################################################################
  # MQTT Broker
  ########################################################################
  mosquitto-mqtt:
    container_name: mosquitto-mqtt
    image: eclipse-mosquitto:latest
    networks:
      home_internal:
        ipv4_address: 192.168.89.253 # You can specify a static IP
    security_opt:
      - no-new-privileges:true
    restart: always
    volumes:
      - $DOCKERDIR/appdata/mosquitto:/mosquitto
      - $DOCKERDIR/appdata/mosquitto/data:/mosquitto/data
      - $DOCKERDIR/appdata/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID

  ########################################################################
  # HomeAssistant
  ########################################################################
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $HAHOMEDIR:/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    security_opt:
      - no-new-privileges:true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    depends_on:
      - traefik
    restart: always
    networks:
      home_internal:
        ipv4_address: 192.168.89.251 # Otherwise NodeRed won't know where to look
      dockervlan:
        ipv4_address: 192.168.1.199 # IP address inside the defined rangeIp
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.homeassistant-rtr.entrypoints=https"
      - "traefik.http.routers.homeassistant-rtr.rule=Host(`homeassistant.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.homeassistant-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.homeassistant-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.homeassistant-rtr.service=homeassistant-svc"
      - "traefik.http.services.homeassistant-svc.loadbalancer.server.port=8123"
      ## Watchtower manual update
      - "com.centurylinklabs.watchtower.enable=false"

  ########################################################################
  # File Browser - Explorer
  ########################################################################
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    ports:
      - "81:80"
    volumes:
      - $DOCKERDIR/appdata/filebrowser:/config
      - $EXTDRIVE:/srv
      - $DOCKERDIR/appdata/filebrowser/database:/database/
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    networks:
      home_internal:
    security_opt:
      - no-new-privileges:true
    restart: always
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.filebrowser-rtr.entrypoints=https"
      - "traefik.http.routers.filebrowser-rtr.rule=Host(`fb.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.filebrowser-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.filebrowser-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.filebrowser-rtr.service=filebrowser-svc"
      - "traefik.http.services.filebrowser-svc.loadbalancer.server.port=80"