version: "3.9"

########################################################################
########################### NETWORKS ###################################
########################################################################
networks:
  home_internal:
    name: home_internal
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.89.0/24
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts:
      parent: enp3s0 # using ifconfig
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          ip_range: "192.168.1.199/32"
          gateway: "192.168.1.1"