version: "3.9"

########################################################################
########################### Extensions #################################
########################################################################
x-environment:
  &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

# Keys common to some of the services in basic-services.txt
x-common-keys-core:
  &common-keys-core
  networks:
    - home_internal
  security_opt:
    - no-new-privileges:true
  restart: always

# Keys common to some of the dependent services/apps
x-common-keys-apps:
  &common-keys-apps
  networks:
    - home_internal
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped

########################################################################
########################### SERVICES ###################################
########################################################################
services:
  estalor-yocto:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    image: estalor-yocto:latest
    container_name: estalor-yocto
    stdin_open: true
    tty: true
    networks:
      home_internal:
        ipv4_address: 192.168.89.252 # You can specify a static IP
    volumes:
      - $YOCTOCACHEDIR:/cache
      - $DOCKERDIR/appdata/estalor-yocto:/home/yocto
