version: "3.9"

########################################################################
########################### Extensions #################################
########################################################################
x-environment:
  &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

# Keys common to some of the services in basic-services.txt
x-common-keys-core:
  &common-keys-core
  networks:
    - home_internal
  security_opt:
    - no-new-privileges:true
  restart: always

# Keys common to some of the dependent services/apps
x-common-keys-apps:
  &common-keys-apps
  networks:
    - home_internal
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped

########################################################################
########################### SERVICES ###################################
########################################################################
services:
  ########################################################################
  # Wekan - Kanban board
  ########################################################################
  # ----------------------------------------------------------------------------------
  # ===== INSIDE DOCKER CONTAINERS, AND BACKUP/RESTORE ====
  # https://github.com/wekan/wekan/wiki/Backup
  # If really necessary, repair MongoDB: https://github.com/wekan/wekan-mongodb/issues/6#issuecomment-424004116
  # 1) Going inside containers:
  #    a) Wekan app, does not contain data
  #         docker exec -it wekan-app bash
  #    b) MongoDB, contains all data
  #         docker exec -it wekan-db bash
  # 2) Copying database to outside of container:
  #      docker exec -it wekan-db bash
  #      cd /data
  #      mongodump
  #      exit
  #      docker cp wekan-db:/data/dump .
  # 3) Restoring database
  #      # 1) Stop wekan
  #             docker stop wekan-app
  #      # 2) Go inside database container
  #             docker exec -it wekan-db bash
  #      # 3) and data directory
  #             cd /data
  #      # 4) Remove previous dump
  #             rm -rf dump
  #      # 5) Exit db container
  #             exit
  #      # 6) Copy dump to inside docker container
  #             docker cp dump wekan-db:/data/
  #      # 7) Go inside database container
  #             docker exec -it wekan-db bash
  #      # 8) and data directory
  #             cd /data
  #      # 9) Restore
  #             mongorestore --drop
  #      # 10) Exit db container
  #             exit
  #      # 11) Start wekan
  #             docker start wekan-app
  #-------------------------------------------------------------------------

  wekandb:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    image: mongo:6
    container_name: wekan-db
    command: mongod --logpath /dev/null --oplogSize 128 --quiet
    expose:
      - $WEKANDB_PORT
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - $DOCKERDIR/appdata/wekan-db:/data/db
      - $DOCKERDIR/appdata/wekan-db/configdb:/data/configdb
      - $DOCKERDIR/appdata/wekan-db-dump:/dump

  wekan:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    image: quay.io/wekan/wekan:latest
    container_name: wekan-app
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.wekan-rtr.entrypoints=https"
      - "traefik.http.routers.wekan-rtr.rule=Host(`wekan.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.wekan-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.wekan-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.wekan-rtr.service=wekan-svc"
      - "traefik.http.services.wekan-svc.loadbalancer.server.port=8080"
    depends_on:
      - wekandb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKERDIR/appdata/wekan-files:/data:rw
    environment:
      #-----------------------------------------------------------------
      # ==== WRITEABLE PATH FOR FILE UPLOADS ====
      - WRITABLE_PATH=/data
      # ==== MONGO_URL ====
      - MONGO_URL=mongodb://wekandb:$WEKABDB_PORT/wekan
      #---------------------------------------------------------------
      # ==== ROOT_URL SETTING ====
      - ROOT_URL=http://localhost #   <=== using only at same laptop/desktop where Wekan is installed
      #---------------------------------------------------------------
      # ==== EMAIL SETTINGS ====
      - MAIL_URL=smtp://<mail_url>:25/?ignoreTLS=true&tls={rejectUnauthorized:false}
      - MAIL_FROM=Wekan Notifications <noreply.wekan@mydomain.com>
      #---------------------------------------------------------------
      # ==== WEKAN API AND EXPORT BOARD ====
      - WITH_API=true
      #---------------------------------------------------------------
      # ==== RICH TEXT EDITOR IN CARD COMMENTS ====
      # https://github.com/wekan/wekan/pull/2560
      - RICHER_CARD_COMMENT_EDITOR=false
      #---------------------------------------------------------------
      # ==== CARD OPENED, SEND WEBHOOK MESSAGE ====
      # https://github.com/wekan/wekan/issues/2518
      - CARD_OPENED_WEBHOOK_ENABLED=false
      #---------------------------------------------------------------
      - BIGEVENTS_PATTERN=NONE
      #-----------------------------------------------------------------
      # ==== BROWSER POLICY AND TRUSTED IFRAME URL ====
      - BROWSER_POLICY_ENABLED=true
