version: "3.9"

########################################################################
########################### Extensions #################################
########################################################################
x-environment:
  &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

# Keys common to some of the services in basic-services.txt
x-common-keys-core:
  &common-keys-core
  networks:
    - home_internal
  security_opt:
    - no-new-privileges:true
  restart: always

# Keys common to some of the dependent services/apps
x-common-keys-apps:
  &common-keys-apps
  networks:
    - home_internal
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped

########################################################################
########################### SERVICES ###################################
########################################################################
services:
  ########################################################################
  # NodeRed
  ########################################################################
  nodered:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    container_name: nodered
    image: nodered/node-red
    restart: unless-stopped
    environment:
      <<: *default-tz-puid-pgid
    volumes:
      - $DOCKERDIR/appdata/nodered/data:/data
    ports:
      - "1880:1880"
    depends_on:
      - home-assistant
      - mosquitto-mqtt
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.nodered-rtr.entrypoints=https"
      - "traefik.http.routers.nodered-rtr.rule=Host(`nodered.$DOMAINNAME_CLOUD_SERVER`)"
      ## Middlewares
      - "traefik.http.routers.nodered-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.nodered-rtr.service=nodered-svc"
      - "traefik.http.services.nodered-svc.loadbalancer.server.port=1880"
      ## Watchtower manual update
      - "com.centurylinklabs.watchtower.enable=false"

  ########################################################################
  # MQTT Broker
  ########################################################################
  mosquitto-mqtt:
    <<: *common-keys-apps # See EXTENSION FIELDS at the top
    container_name: mosquitto-mqtt
    image: eclipse-mosquitto:latest
    networks:
      home_internal:
        ipv4_address: 192.168.89.253 # You can specify a static IP
    volumes:
      - $DOCKERDIR/appdata/mosquitto:/mosquitto
      - $DOCKERDIR/appdata/mosquitto/data:/mosquitto/data
      - $DOCKERDIR/appdata/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    environment:
      <<: *default-tz-puid-pgid

  ########################################################################
  # HomeAssistant
  ########################################################################
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $HAHOMEDIR:/config
    environment:
      <<: *default-tz-puid-pgid
    security_opt:
      - no-new-privileges:true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: always
    networks:
      home_internal:
        ipv4_address: 192.168.89.16 # Otherwise NodeRed won't know where to look
      dockervlan:
        ipv4_address: 192.168.1.199 # IP address inside the defined range
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.homeassistant-rtr.entrypoints=https"
      - "traefik.http.routers.homeassistant-rtr.rule=Host(`homeassistant.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.homeassistant-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.homeassistant-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.homeassistant-rtr.service=homeassistant-svc"
      - "traefik.http.services.homeassistant-svc.loadbalancer.server.port=8123"
      ## Watchtower manual update
      - "com.centurylinklabs.watchtower.enable=false"
