version: "3.9"

########################################################################
########################### SERVICES ###################################
########################################################################
services:
  ########################################################################
  # NodeRed
  ########################################################################
  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    networks:
      home_internal:
    security_opt:
      - no-new-privileges:true
    restart: always
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    volumes:
      - $DOCKERDIR/appdata/nodered/data:/data
    ports:
      - "$NODERED_PORT:1880"
    depends_on:
      - home-assistant
      - mosquitto-mqtt
    labels:
      - "traefik.enable=true"
      ## HTTP Access
      - "traefik.http.routers.nodered-http-router.entrypoints=https"
      - "traefik.http.routers.nodered-http-router.rule=Host(`nodered.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.nodered-http-router.tls=true"
      - "traefik.http.routers.nodered-http-router.middlewares=chain-oauth@file"
      - "traefik.http.routers.nodered-http-router.service=nodered-http-service"
      - "traefik.http.services.nodered-http-service.loadbalancer.server.port=1880"
      ## Watchtower manual update
      - "com.centurylinklabs.watchtower.enable=true"

  ########################################################################
  # MQTT Broker
  ########################################################################
  mosquitto-mqtt:
    container_name: mosquitto-mqtt
    image: eclipse-mosquitto:latest
    networks:
      home_internal:
        ipv4_address: $MOSQUITTO_IP # You can specify a static IP
    security_opt:
      - no-new-privileges:true
    restart: always
    volumes:
      - $DOCKERDIR/appdata/mosquitto:/mosquitto
      - $DOCKERDIR/appdata/mosquitto/data:/mosquitto/data
      - $DOCKERDIR/appdata/mosquitto/log:/mosquitto/log
    ports:
      - $MQTTBROKER_PORT1:1883
      - $MQTTBROKER_PORT2:9001
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID

  ########################################################################
  # HomeAssistant
  ########################################################################
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $HAHOMEDIR:/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    security_opt:
      - no-new-privileges:true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: always
    networks:
      home_internal:
        ipv4_address: $HOMEASSISTANT_INTERNAL_IP # Otherwise NodeRed won't know where to look
      dockervlan:
        ipv4_address: $HOMEASSISTANT_EXTERNAL_IP # IP address inside the defined rangeIp
    labels:
      - "traefik.enable=true"
      ## HTTP Access
      - "traefik.http.routers.homeassistant-http-router.entrypoints=https"
      - "traefik.http.routers.homeassistant-http-router.rule=Host(`homeassistant.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.homeassistant-http-router.tls=true"
      - "traefik.http.routers.homeassistant-http-router.middlewares=chain-oauth@file"
      - "traefik.http.routers.homeassistant-http-router.service=homeassistant-http-service"
      - "traefik.http.services.homeassistant-http-service.loadbalancer.server.port=8123"
      ## Watchtower manual update
      - "com.centurylinklabs.watchtower.enable=false"

  ########################################################################
  # File Browser - Explorer
  ########################################################################
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    ports:
      - "$FILEBROWSER_PORT:80"
    volumes:
      - $DOCKERDIR/appdata/filebrowser:/config
      - $EXTDRIVE:/srv
      - $DOCKERDIR/appdata/filebrowser/database:/database/
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    networks:
      home_internal:
    security_opt:
      - no-new-privileges:true
    restart: always
    labels:
      - "traefik.enable=true"
      ## HTTP Access
      - "traefik.http.routers.filebrowser-http-router.entrypoints=https"
      - "traefik.http.routers.filebrowser-http-router.rule=Host(`fb.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.filebrowser-http-router.tls=true"
      - "traefik.http.routers.filebrowser-http-router.middlewares=chain-oauth@file"
      - "traefik.http.routers.filebrowser-http-router.service=filebrowser-svc"
      - "traefik.http.services.filebrowser-svc.loadbalancer.server.port=80"