version: "3.9"

########################################################################
########################### SERVICES ###################################
########################################################################
services:
  ########################################################################
  # Jenkins
  ########################################################################
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8081:8080
      # - 50000:50000
    container_name: jenkins
    networks:
      home_internal:
      socket_proxy:
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375 # Use this if you have Socket Proxy enabled.
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    volumes:
      - $DOCKERDIR/appdata/jenkins:/var/jenkins_home
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.jenkins-rtr.entrypoints=https"
      - "traefik.http.routers.jenkins-rtr.rule=Host(`jenkins.$DOMAINNAME_CLOUD_SERVER`)"
      ## Middlewares
      - "traefik.http.routers.jenkins-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.jenkins-rtr.service=jenkins-svc"
      - "traefik.http.services.jenkins-svc.loadbalancer.server.port=8080"
      ## Watchtower manual update
      - "com.centurylinklabs.watchtower.enable=false"

  ########################################################################
  # VSCode
  ########################################################################
  vscode:
    image: lscr.io/linuxserver/code-server:latest
    container_name: vscode
    ports:
      - "$VSCODE_PORT:8443"
    volumes:
      - $DOCKERDIR:/data/docker
      - $HAHOMEDIR:/data/homeassistant
      - $HOMEDIR:/data/home
      - $DOCKERDIR/appdata/vscode:/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      DOCKER_HOST: tcp://socket-proxy:2375
    networks:
      socket_proxy:
      home_internal:
    security_opt:
      - no-new-privileges:true
    restart: always
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.vscode-rtr.entrypoints=https"
      - "traefik.http.routers.vscode-rtr.rule=Host(`code.$DOMAINNAME_CLOUD_SERVER`)"
      ## Middlewares
      - "traefik.http.routers.vscode-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.vscode-rtr.service=vscode-svc"
      - "traefik.http.services.vscode-svc.loadbalancer.server.port=8443"

  ########################################################################
  # Guacd - Guacamole daemon
  ########################################################################
  guacd:
    image: guacamole/guacd
    container_name: guacd
    networks:
      home_internal:
    security_opt:
      - no-new-privileges:true
    restart: always

  ########################################################################
  # Guacamole - Remote desktop, SSH, on Telnet on any HTML5 Browser
  ########################################################################
  # Create all databases and tables first
  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mariadb-guacemole
      MYSQL_PORT: $GUACDB_PORT
      MYSQL_DATABASE: guacemole
      MYSQL_USER: $GUAC_MYSQL_USER
      MYSQL_PASSWORD: $GUACEMOLE_PASSWORD
    networks:
      home_internal:
    security_opt:
      - no-new-privileges:true
    restart: always
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.guacamole-rtr.entrypoints=https"
      - "traefik.http.routers.guacamole-rtr.rule=Host(`guacamole.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.guacamole-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.guacamole-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.guacamole-rtr.service=guacamole-svc"
      - "traefik.http.services.guacamole-svc.loadbalancer.server.port=8080"

  ########################################################################
  # Portainer - WebUI for Containers
  ########################################################################
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    command: -H tcp://socket-proxy:2375
    volumes:
      - $DOCKERDIR/appdata/portainer/data:/data
    environment:
      - TZ=$TZ
    ports:
      - "9000:9000"
    networks:
      home_internal:
      socket_proxy:
    security_opt:
      - no-new-privileges:true
    restart: always
    depends_on:
      - socket-proxy
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.portainer-rtr.entrypoints=https"
      - "traefik.http.routers.portainer-rtr.rule=Host(`portainer.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.portainer-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.nodered-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.portainer-rtr.service=portainer-svc"
      - "traefik.http.services.portainer-svc.loadbalancer.server.port=9000"

  ########################################################################
  # Heimdall - Container dashboard
  ########################################################################
  heimdall:
    container_name: heimdall
    image: lscr.io/linuxserver/heimdall:latest
    networks:
      home_internal:
      socket_proxy:
    security_opt:
      - no-new-privileges:true
    restart: always
    volumes:
      - $DOCKERDIR/appdata/heimdall:/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      DOCKER_HOST: tcp://socket-proxy:2375
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.heimdall-rtr.entrypoints=https"
      - "traefik.http.routers.heimdall-rtr.rule=Host(`$DOMAINNAME_CLOUD_SERVER`,`www.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.heimdall-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.heimdall-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.heimdall-rtr.service=heimdall-svc"
      - "traefik.http.services.heimdall-svc.loadbalancer.server.port=80"

  ########################################################################
  # Dozzle - Runtime insight in running containers
  ########################################################################
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    networks:
      - home_internal
      - socket_proxy
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      DOZZLE_FILTER: "status=running"
      DOCKER_HOST: tcp://socket-proxy:2375
    security_opt:
      - no-new-privileges:true
    restart: always
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.dozzle-rtr.entrypoints=https"
      - "traefik.http.routers.dozzle-rtr.rule=Host(`dozzle.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.dozzle-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.dozzle-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.dozzle-rtr.service=dozzle-svc"
      - "traefik.http.services.dozzle-svc.loadbalancer.server.port=8080"