services:
  ########################################################################
  # Docker-GC - Automatic cleanup of images and containers
  ########################################################################
  dockergc:
    container_name: docker-gc
    image: clockworksoul/docker-gc-cron:latest
    networks:
      socket_proxy:
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/appdata/docker-gc/docker-gc-exclude:/etc/docker-gc-exclude # Create empty file
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375
      CRON: 0 0 0 * * ? # Everyday at midnight. Previously 0 0 * * *
      FORCE_IMAGE_REMOVAL: 1
      FORCE_CONTAINER_REMOVAL: 0
      GRACE_PERIOD_SECONDS: 604800
      DRY_RUN: 0
      CLEAN_UP_VOLUMES: 1
      TZ: $TZ