services:
  ########################################################################
  # Portainer - WebUI for Containers
  ########################################################################
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    command: -H tcp://socket-proxy:2375
    volumes:
      - $DOCKERDIR/appdata/portainer/data:/data
    environment:
      - TZ=$TZ
    ports:
      - "$PORTAINER_PORT:9000"
    networks:
      - home_internal
      - socket_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on:
      - socket-proxy
    labels:
      - "traefik.enable=true"
      ## HTTP Access
      - "traefik.http.routers.portainer-http-router.entrypoints=https"
      - "traefik.http.routers.portainer-http-router.rule=Host(`portainer.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.portainer-http-router.tls=true"
      - "traefik.http.routers.portainer-http-router.middlewares=chain-oauth@file"
      - "traefik.http.routers.portainer-http-router.service=portainer-http-service"
      - "traefik.http.services.portainer-http-service.loadbalancer.server.port=9000"