services:
  yocto-local:
    container_name: yocto-local
    image: gitea.estalor.com/tom/yocto-builder:latest
    tty: true
    networks:
      home_internal:
      # dockervlan:
      #   ipv4_address: $HOMEASSISTANT_TEST_EXTERNAL_IP
    ports:
      - "$YOCTO_TOASTER_PORT:8000"
      - "$YOCTO_VNC_PORT:5900"
      - "$YOCTO_HA_PORT:8888"
      - "$YOCTO_SSH_PORT:2222"
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    volumes:
      - /cache:/cache
      - $YOCTO_PROJECT_PATH:$YOCTO_PROJECT_PATH
    environment:
      - TEMPLATECONF=$YOCTO_TEMPLATE_CONF